### ISSUE TITLE
Add *.shp to strandard files

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/tool-specs#14]
We could add shapefiles (`*.shp`) to the standard file types. Shapefiles could then always be transformed to `*.geojson` or `*.geopackage` files.  
I think it would be a good idea to directly parse shapefiles / geospatial data with the `json2args` packages. I had to convert a `.shp` file to `.geojson` for another tool before and it would be nice to be sure that we always expect out geospatial input data in the same format.

First discussed here:
> `Shapefile.shp` is not a good name, as the parameter is then also called `Shapefile`. Rather use a parameter name that is more descriptive, like: `gauges`, which would result in `gauges.shp`. 
> 
> In addition: @AlexDo1 maybe we add `*.shp` to the standard file types, but always transform it to `*.geojson`. or `*.geopackage` That makes handling geospatial data easier. We can open a discussion for that in the tool-specs

_Originally posted by @mmaelicke in https://github.com/VForWaTer/tool_whiteboxgis/pull/10#discussion_r1217612466_

**Comment by mmaelicke** [comment]
This is obsolete, as the `data.extension` can limit the data input to literally any kind of data file extensions
