### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/tool-specs#16]
@AlexDo1 we could add a new top level folder with some example `tool.yml` and `input.json` files / folders that span all possible input parameter / data and combinations.
The idea is, that whenever we change the specs (like we are doing right now), we can change the checkmarks in the main table as the associated packages (json2args, json2aRgs, etc) do not fail on the test-cases anymore.
For the beginning we would check that by hand (later we might use a GH action for that).

**Comment by AlexDo1** [comment]
I think that is a good idea to clearly track what we have implemented already.

**Comment by mmaelicke** [comment]
We kind of indirectly agreed to move testing into the client libraries.
