### ISSUE TITLE
Rename tool.json to parameters.json

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/tool-specs#3]
As [tool.json](https://github.com/VForWaTer/tool_template_python/blob/main/in/tool.json) exclusively contains input parameters for the tools, we should rename the file to `parameters.json`.

We have to do this in a lot of packages:
- [x] [json2args](https://github.com/hydrocode-de/json2args)
- [x] tool templates
- [x] implemented tools

**Comment by mmaelicke** [comment]
This should be finsihed everywhere, right?

**Comment by AlexDo1** [comment]
I just looked through all the [V-For-WaTer tools](https://github.com/orgs/VForWaTer/repositories?language=&q=tool&sort=&type=all) and the parameter file is renamed to `parameters.json` everywhere, so I close this issue.
